version: 2.1
jobs:
  test:
    machine:
      node-version:
        type: string
      steps:
        - checkout
        - run: npm test



workflows:

  all-tests:
    jobs:
      - test:
        - mersion:
          node-version: "18.12.1"
   




    
  
