version: 2.1
jobs:
  test:
    node-version:
      type: string
    steps:
      - checkout
      - run: npm test



workflows:

  all-tests:
    jobs:
      - test:
        node-version: "18.12.1"
   




    
  
