version: 2.1
jobs:
  - test:
    machine:
      node:
        version: 18.12.1
  - npm test


  all-tests:
    jobs:
      - test:
        - mersion:
          node-version: "18.12.1"
   




    
  
